### ISSUE TITLE
Please add a way to add song via script or import using JSON

### ISSUE THREAD

**Issue by tsuki-tsuki** [holyrics/jslib#10]
There’s a feature to export song lyrics to JSON complete with the translations. But there’s no import function using the same JSON.

If possible, please add import feature using the same JSON format used at export.

Also if possible please add method using JS to add new song with same format as JSON (including translations).

**Comment by holyrics** [comment]
Hello,

In the update released today `v2.23.0`, the possibility of importing songs using javascript was implemented, and the javascript code that imports the json file generated in the export option was also implemented.

About adding a new song using the javascript method, it is currently not available via code, perhaps in the future I will implement a solution, but alternatively you can use the solution via API over the local network

More details at: [https://github.com/holyrics/Scripts/blob/main/ApiPopupCreateSong.md](https://github.com/holyrics/Scripts/blob/main/ApiPopupCreateSong.md)

This API option, in today's update, accepts other fields in addition to those currently documented.
The documentation will be updated soon.
The basic structure of the payload is:

```json
{
  "title": "title",
  "title_translations": {
    "key1": "value",
    "key2": "value"
  },
  "artist": "artist",
  "author": "author",
  "note": "note",
  "copyright": "copyright",
  "key": "",
  "bpm": 0.0,
  "time_sig": "",
  "paragraphs": [
    {
      "text": "Slide 1\nSlide 1",
      "description": "",
      "translations": {
        "key1": "value",
        "key2": "value"
      }
    }, {
      "text": "Slide 2\nSlide 2",
      "description": "",
      "translations": {
        "key1": "value",
        "key2": "value"
      }
    }
  ],
  "streaming": {
    "audio": {
      "spotify": "spotify_id",
      "youtube": "youtube_id",
      "deezer": "deezer_id"
    },
    "backing_track": {
      "spotify": "spotify_id",
      "youtube": "youtube_id",
      "deezer": "deezer_id"
    }
  },
  "extras": {
    "extra": "",
    "key1": "value",
    "key2": "value"
  }
}
```
