### ISSUE TITLE
Requisitar a uma api qualquer na Web.

### ISSUE THREAD

**Issue by AntonioGomes42** [holyrics/jslib#6]
Boa noite, estou sem entender como posso requisitar os dados para uma api qualquer da web, através do **websearch(javascript)** , seria para fazer a requisição passando parametros, pegar o json de resposta e tratar este no javascript.

**Comment by holyrics** [comment]
[https://github.com/holyrics/Scripts/blob/main/WebSearch_JavaScript.md](https://github.com/holyrics/Scripts/blob/main/WebSearch_JavaScript.md)
