### ISSUE TITLE
Is there any web interface to use it ?

### ISSUE THREAD

**Issue by sostenesapollo** [holyrics/jslib#8]
Ive bougth the ios version, but it is incomplete if compared dto the android version, i.e; it is not able to search new songs on the internet, So I was thinking in create a local web app to use it instead of use the ios app...

**Comment by sostenesapollo** [comment]
Also, I always have network issues, So I always need to reconnect using qrCode what is boring

**Comment by holyrics** [comment]
Não há interface criada, apenas a api está disponível.
https://github.com/holyrics/API-Server
Você pode criar sua própria interface para alguma ação ou funcionalidade que precisar.
